"""Generate markdown report and optional alerts."""

from __future__ import annotations

import json
import logging
import math
from datetime import date
from pathlib import Path
from typing import Any

from src.config import get_path

logger = logging.getLogger(__name__)


def _format_runway(months: float) -> str:
    """Render runway as 'inf' when there is no burn, otherwise one decimal."""
    return "inf" if not math.isfinite(months) else f"{months:.1f}"


def _json_safe(kpis: dict[str, float]) -> dict[str, float | None]:
    """Replace non-finite floats with None so the alert stays valid JSON."""
    return {
        k: (None if isinstance(v, float) and not math.isfinite(v) else v) for k, v in kpis.items()
    }


def write_report(
    kpis: dict[str, float],
    n_anomalies: int,
    commentary: str,
    cfg: dict[str, Any],
    report_date: str | None = None,
) -> Path:
    """Write a concise markdown report to reports/."""
    report_date = report_date or date.today().isoformat()
    reports_dir = get_path(cfg, "reports")
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"report_{report_date}.md"

    md = f"""# Financial Operations Report - {report_date}

## Headline KPIs

| Metric | Value |
|--------|------:|
| Total Income | {kpis.get("total_income", 0):,.2f} EUR |
| Total Expenses | {kpis.get("total_expenses", 0):,.2f} EUR |
| Net Cash Flow | {kpis.get("net_cash_flow", 0):,.2f} EUR |
| Burn Rate (trailing) | {kpis.get("burn_rate", 0):,.2f} EUR/mo |
| Margin | {kpis.get("margin", 0) * 100:.1f} % |
| Runway | {_format_runway(kpis.get("runway_months", 0.0))} months |
| MoM Net Variance | {kpis.get("mom_variance_pct", 0):+.1f} % |
| Anomalies Flagged | {n_anomalies} |

## AI Commentary

{commentary}

---
*Generated by financial-operations-analytics (simulation)*
"""
    path.write_text(md, encoding="utf-8")
    logger.info("Report written -> %s", path)
    return path


def check_and_alert(
    kpis: dict[str, float],
    n_anomalies: int,
    cfg: dict[str, Any],
    report_date: str | None = None,
) -> Path | None:
    """Raise alert file if thresholds breached."""
    report_date = report_date or date.today().isoformat()
    thr_count = cfg["anomaly"]["alert_threshold_count"]
    thr_pct = cfg["anomaly"]["cashflow_deviation_pct"]

    reasons: list[str] = []
    if n_anomalies > thr_count:
        reasons.append(f"Anomaly count {n_anomalies} > threshold {thr_count}")
    if abs(kpis.get("mom_variance_pct", 0)) > thr_pct:
        reasons.append(
            f"MoM net variance {kpis.get('mom_variance_pct', 0):.1f}% exceeds +/-{thr_pct}%"
        )

    if not reasons:
        logger.info("No alert thresholds breached")
        return None

    alerts_dir = get_path(cfg, "alerts")
    alerts_dir.mkdir(parents=True, exist_ok=True)
    alert_path = alerts_dir / f"{report_date}.json"
    payload = {
        "date": report_date,
        "reasons": reasons,
        "kpis": _json_safe(kpis),
        "n_anomalies": n_anomalies,
    }
    alert_path.write_text(json.dumps(payload, indent=2, allow_nan=False), encoding="utf-8")
    logger.warning("ALERT written -> %s | %s", alert_path, "; ".join(reasons))
    print(f"\n[ALERT] {'; '.join(reasons)}\n   Details: {alert_path}\n")
    return alert_path
